### ISSUE TITLE
undefined method User::getEffectiveGroups()

### ISSUE THREAD

**Issue by perjes** [debtcompliance/EmailPage#6]
Hi!
I'm trying to use extension on MW 1.39.5 and get the error:

"MediaWiki internal error.

Original exception: [0c9a5c9f5069691bf45e8bd8] /last_of_us/index.php/Main_page Error: Call to undefined method User::getEffectiveGroups()
Backtrace:
from /var/www/html/last_of_us/extensions/EmailPage/EmailPage_body.php(54)
#0 /var/www/html/last_of_us/includes/HookContainer/HookContainer.php(338): EmailPage::onSkinTemplateNavigationUniversal()
#1 /var/www/html/last_of_us/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#2 /var/www/html/last_of_us/includes/HookContainer/HookRunner.php(3543): MediaWiki\HookContainer\HookContainer->run()
#3 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(1203): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation__Universal()
#4 /var/www/html/last_of_us/skins/Vector/includes/SkinVector.php(350): SkinTemplate->runOnSkinTemplateNavigationHooks()
#5 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(1574): MediaWiki\Skins\Vector\SkinVector->runOnSkinTemplateNavigationHooks()
#6 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(790): SkinTemplate->buildContentNavigationUrlsInternal()
#7 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(229): SkinTemplate->getPortletsTemplateData()
#8 /var/www/html/last_of_us/includes/skins/SkinMustache.php(88): SkinTemplate->getTemplateData()
#9 /var/www/html/last_of_us/skins/Vector/includes/SkinVector.php(454): SkinMustache->getTemplateData()
#10 /var/www/html/last_of_us/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Vector\SkinVector->getTemplateData()
#11 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(177): SkinMustache->generateHTML()
#12 /var/www/html/last_of_us/includes/OutputPage.php(2876): SkinTemplate->outputPage()
#13 /var/www/html/last_of_us/includes/MediaWiki.php(922): OutputPage->output()
#14 /var/www/html/last_of_us/includes/MediaWiki.php(562): MediaWiki->main()
#15 /var/www/html/last_of_us/index.php(50): MediaWiki->run()
#16 /var/www/html/last_of_us/index.php(46): wfIndexMain()
#17 {main}"

$ php showJobs.php
PHP Deprecated:  Premature access to service container [Called from EmailPage::onRegistration in /var/www/html/last_of_us/extensions/EmailPage/EmailPage_body.php at line 28] in /var/www/html/last_of_us/includes/debug/MWDebug.php on line 381
PHP Deprecated:  Premature access to service 'HookContainer' [Called from MediaWiki\MediaWikiServices::getInstance in /var/www/html/last_of_us/includes/MediaWikiServices.php at line 289] in /var/www/html/last_of_us/includes/debug/MWDebug.php on line 381
PHP Deprecated:  Premature access to service 'ObjectFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /var/www/html/last_of_us/includes/ServiceWiring.php at line 721] in /var/www/html/last_of_us/includes/debug/MWDebug.php on line 381
0

Installed software:
Product	Version
MediaWiki	1.39.5
PHP	7.4.3-4ubuntu2.19 (apache2handler)
MySQL	8.0.36-0ubuntu0.20.04.1
ICU	66.1
Lua	5.1.5
Pygments	2.11.2

**Comment by perjes** [comment]
PHP 8.0 has the same problem

Installed software
Product	Version
MediaWiki	1.39.5
PHP	8.0.30 (fpm-fcgi)
MySQL	8.0.36-0ubuntu0.20.04.1
ICU	66.1
Lua	5.1.5
Pygments	2.11.2



> Hi! I'm trying to use extension on MW 1.39.5 and get the error:
> 
> "MediaWiki internal error.
> 
> Original exception: [0c9a5c9f5069691bf45e8bd8] /last_of_us/index.php/Main_page Error: Call to undefined method User::getEffectiveGroups() Backtrace: from /var/www/html/last_of_us/extensions/EmailPage/EmailPage_body.php(54) #0 /var/www/html/last_of_us/includes/HookContainer/HookContainer.php(338): EmailPage::onSkinTemplateNavigationUniversal() #1 /var/www/html/last_of_us/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook() #2 /var/www/html/last_of_us/includes/HookContainer/HookRunner.php(3543): MediaWiki\HookContainer\HookContainer->run() #3 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(1203): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation__Universal() #4 /var/www/html/last_of_us/skins/Vector/includes/SkinVector.php(350): SkinTemplate->runOnSkinTemplateNavigationHooks() #5 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(1574): MediaWiki\Skins\Vector\SkinVector->runOnSkinTemplateNavigationHooks() #6 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(790): SkinTemplate->buildContentNavigationUrlsInternal() #7 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(229): SkinTemplate->getPortletsTemplateData() #8 /var/www/html/last_of_us/includes/skins/SkinMustache.php(88): SkinTemplate->getTemplateData() #9 /var/www/html/last_of_us/skins/Vector/includes/SkinVector.php(454): SkinMustache->getTemplateData() #10 /var/www/html/last_of_us/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Vector\SkinVector->getTemplateData() #11 /var/www/html/last_of_us/includes/skins/SkinTemplate.php(177): SkinMustache->generateHTML() #12 /var/www/html/last_of_us/includes/OutputPage.php(2876): SkinTemplate->outputPage() #13 /var/www/html/last_of_us/includes/MediaWiki.php(922): OutputPage->output() #14 /var/www/html/last_of_us/includes/MediaWiki.php(562): MediaWiki->main() #15 /var/www/html/last_of_us/index.php(50): MediaWiki->run() #16 /var/www/html/last_of_us/index.php(46): wfIndexMain() #17 {main}"
> 
> $ php showJobs.php PHP Deprecated: Premature access to service container [Called from EmailPage::onRegistration in /var/www/html/last_of_us/extensions/EmailPage/EmailPage_body.php at line 28] in /var/www/html/last_of_us/includes/debug/MWDebug.php on line 381 PHP Deprecated: Premature access to service 'HookContainer' [Called from MediaWiki\MediaWikiServices::getInstance in /var/www/html/last_of_us/includes/MediaWikiServices.php at line 289] in /var/www/html/last_of_us/includes/debug/MWDebug.php on line 381 PHP Deprecated: Premature access to service 'ObjectFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /var/www/html/last_of_us/includes/ServiceWiring.php at line 721] in /var/www/html/last_of_us/includes/debug/MWDebug.php on line 381 0
> 
> Installed software: Product Version MediaWiki 1.39.5 PHP 7.4.3-4ubuntu2.19 (apache2handler) MySQL 8.0.36-0ubuntu0.20.04.1 ICU 66.1 Lua 5.1.5 Pygments 2.11.2

**Comment by absort0** [comment]
Thank you for taking the time of submitting this issue, @perjes.
It is strange that the wikis we have are not impacted by this issue, even though we have a similar stack. We are running:


Product | Version
-- | --
MediaWiki | 1.39.6
PHP | 8.1.27 (fpm-fcgi)
MariaDB | 10.5.23-MariaDB-0+deb11u1
ICU | 67.1
Elasticsearch | 7.10.1

Anyway, it is a good catch, as the method that is causing this has been removed in version 1.38, we are probably not calling the methods that have this lines. 

Would be so kind as to test using this branch and see if it works for you? 
https://github.com/debtcompliance/EmailPage/tree/effective-groups

**Comment by perjes** [comment]
Thanks, @absort0  !
this version works for me
> 
> Would be so kind as to test using this branch and see if it works for you? https://github.com/debtcompliance/EmailPage/tree/effective-groups

**Comment by absort0** [comment]
commits fb96620 and 450da8c have fixed the issue, closing.
